---
 - name: Create three new IAM users
   iam:
     iam_type: user
     name: "{{ item }}"
     state: present
     password: "Mypass@123"
     access_key_state: create
   with_items: '{{ username }}'
