apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ deploymentName }}
spec:
  replicas: {{ numberOfReplicas }}
  selector:
    matchLabels:
      app: {{ appLevel }}
  template:
    metadata:
      labels:
        app: {{ appLevel }}
    spec:
      containers:
      - name: {{ containerName }}
        image: {{ image }}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ serviceName }}
spec:
  type: NodePort
  selector:
    app: {{ appLevel }}
  ports:
    - port: 80
      targetPort: 80
      nodePort: {{ nodePort }}
