---
  - name: update packages
    shell: apt-get update
  - name: install apache
    apt:
      name: apache2
      state: latest
  - name: copy files to remote node
    template: src=templates/index.html dest={{ dest_path }}
    notify: 
    - restart and enable apache
# tasks file for my_web_server
